# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website_link',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Personal website url'),
        ),
    ]
