# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_message',
            field=models.CharField(default='check out this video', max_length=500),
        ),
    ]
