# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type_of_vote',
            field=models.IntegerField(choices=[(1, 'Upvote'), (1, 'Downvote'), (1, 'Flag')]),
        ),
    ]
