# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170715_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type_of_vote',
            field=models.IntegerField(choices=[(3, 'Upvote'), (2, 'Downvote'), (1, 'Flag')]),
        ),
    ]
