# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170715_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_reply',
            field=models.IntegerField(default=0),
        ),
    ]
