# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20170719_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['submission_time']},
        ),
    ]
