# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20170719_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-submission_time']},
        ),
    ]
