# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20170719_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type_of_vote',
            field=models.IntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'Flag')]),
        ),
    ]
